### ISSUE TITLE
Include optimized version

### ISSUE THREAD

**Issue by Athas1980** [CodingTrain/Nebula-AppleSoft-Basic#1]
https://github.com/CodingTrain/Nebula-AppleSoft-Basic/blob/794bc1fd675dc8cd9f69f7e21b0edd6d00d4aadb/snake/snake_expanded.a#L51

Doing this is effectively a delay loop like you had before.  A ring buffer should give you better performance.

**Comment by shiffman** [comment]
Thank you! Changing the title of this issue so that I remember to optimize the code as suggested (maybe on next live stream?) and include a version here!

**Comment by Athas1980** [comment]
Well if you find it useful I'm glad. I wasn't sure if you accepted issues on your github repository.  I got recommended the video by youtube. 

I thought the comment I put may be a little to opaque. Anyway enjoyed the video.

**Comment by shiffman** [comment]
I should still do the ring bugger but thanks to #4 from @tuomount it's much improved!

**Comment by Athas1980** [comment]
Its your call. Just as your channel seems to be about coding exercises. I
thought that data structure may be of interest to your audience.

Optimization for limited hardware can be very enlightening. Not to mention
the discussion about trade off of memory vs performance.

**Comment by tuomount** [comment]
I made pull request for snake_expanded.a to have ring buffer. Game speed seems to be much more stable even if snake gets longer. There is still that collision detection to snake which is done in loop so that still slows down. This probably could be overcome if screen could read with peek command just checking that where snake is moving would be empty.

**Comment by shiffman** [comment]
Wonderful!
